export type Expense = {
  id: string;
  amount: number;
  category: string;
  date: string;
  description?: string;
  paidBy?: string;
  paidFor?: string;
  autoGenerated?: boolean;
};

export type RecurringExpense = {
  id: string;
  amount: number;
  category: string;
  description: string;
  paidBy: string;
  paidFor: string;
  frequency: string;
  nextPaymentDate: string;
  userId: string;
  vpa?: string;
};

export type AssetCategory =
  | "saving"
  | "fixed_deposit"
  | "gold"
  | "retirement"
  | "equity"
  | "mutual_funds"
  | "property"
  | "vehicles"
  | "other";

export type NetWorthAsset = {
  id: string;
  userId: string;
  name: string;
  category: AssetCategory;
  trackingType: "value" | "quantity" | "fd";
  quantity?: number;
  unitLabel?: string;
  principal?: number;
  interestRate?: number;
  startDate?: string;
  maturityDate?: string;
  acquiredDate?: string;
  owner?: "PERSON1" | "PERSON2" | "Both";
  notes?: string;
  createdAt: string;
};

export type NetWorthSnapshot = {
  id: string;
  userId: string;
  date: string;
  goldPricePerGram?: number; // kept for legacy / general fallback
  values: {
    [assetId: string]: number;
  };
  unitPrices?: {
    [assetId: string]: number;
  };
  quantities?: {
    [assetId: string]: number;
  };
  createdAt: string;
};

