export type Expense = {
  id: string;
  amount: number;
  category: string;
  date: string;
  description?: string;
  paidBy?: string;
  paidFor?: string;
  autoGenerated?: boolean;
};

export type RecurringExpense = {
  id: string;
  amount: number;
  category: string;
  description: string;
  paidBy: string;
  paidFor: string;
  frequency: string;
  nextPaymentDate: string;
  userId: string;
  vpa?: string;
};
