export enum EXPENSE_CATEGORY_VALUES {
  FOOD = "Food",
  GROCERY = "Grocery",
  SOCIAL = "Social",
  TRANSPORTATION = "Transportation",
  HOUSEHOLD = "Household",
  APPAREL = "Apparel",
  BEAUTY = "Beauty",
  HEALTH = "Health",
  EDUCATION = "Education",
  GIFT = "Gift",
  HOME = "Home",
  SHOPPING = "Shopping",
  BIRTHDAY = "Birthday",
  VACATION = "Vacation",
  MARRIAGE = "Marriage",
  OTHER = "Other",
}

export const EXPENSE_CATEGORY_OPTIONS = [
  {
    value: EXPENSE_CATEGORY_VALUES.FOOD,
    label: EXPENSE_CATEGORY_VALUES.FOOD,
  },
  {
    value: EXPENSE_CATEGORY_VALUES.SOCIAL,
    label: EXPENSE_CATEGORY_VALUES.SOCIAL,
  },
  {
    value: EXPENSE_CATEGORY_VALUES.TRANSPORTATION,
    label: EXPENSE_CATEGORY_VALUES.TRANSPORTATION,
  },
  {
    value: EXPENSE_CATEGORY_VALUES.HOUSEHOLD,
    label: EXPENSE_CATEGORY_VALUES.HOUSEHOLD,
  },
  {
    value: EXPENSE_CATEGORY_VALUES.APPAREL,
    label: EXPENSE_CATEGORY_VALUES.APPAREL,
  },
  {
    value: EXPENSE_CATEGORY_VALUES.BEAUTY,
    label: EXPENSE_CATEGORY_VALUES.BEAUTY,
  },
  {
    value: EXPENSE_CATEGORY_VALUES.HEALTH,
    label: EXPENSE_CATEGORY_VALUES.HEALTH,
  },
  {
    value: EXPENSE_CATEGORY_VALUES.EDUCATION,
    label: EXPENSE_CATEGORY_VALUES.EDUCATION,
  },
  {
    value: EXPENSE_CATEGORY_VALUES.GIFT,
    label: EXPENSE_CATEGORY_VALUES.GIFT,
  },
  {
    value: EXPENSE_CATEGORY_VALUES.HOME,
    label: EXPENSE_CATEGORY_VALUES.HOME,
  },
  {
    value: EXPENSE_CATEGORY_VALUES.SHOPPING,
    label: EXPENSE_CATEGORY_VALUES.SHOPPING,
  },
  {
    value: EXPENSE_CATEGORY_VALUES.BIRTHDAY,
    label: EXPENSE_CATEGORY_VALUES.BIRTHDAY,
  },
  {
    value: EXPENSE_CATEGORY_VALUES.VACATION,
    label: EXPENSE_CATEGORY_VALUES.VACATION,
  },
  {
    value: EXPENSE_CATEGORY_VALUES.MARRIAGE,
    label: EXPENSE_CATEGORY_VALUES.MARRIAGE,
  },
  {
    value: EXPENSE_CATEGORY_VALUES.OTHER,
    label: EXPENSE_CATEGORY_VALUES.OTHER,
  },
];
