export enum RECURRING_FREQUENCY {
  DAILY = "Daily",
  WEEKLY = "Weekly",
  MONTHLY = "Monthly",
  YEARLY = "Yearly",
}

export const RECURRING_FREQUENCY_OPTIONS = [
  { value: RECURRING_FREQUENCY.DAILY, label: RECURRING_FREQUENCY.DAILY },
  { value: RECURRING_FREQUENCY.WEEKLY, label: RECURRING_FREQUENCY.WEEKLY },
  { value: RECURRING_FREQUENCY.MONTHLY, label: RECURRING_FREQUENCY.MONTHLY },
  { value: RECURRING_FREQUENCY.YEARLY, label: RECURRING_FREQUENCY.YEARLY },
];
