import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { PERSONS } from "@/lib/constants";
import { getAmountLabel } from "@/lib/utils";
import useConfigStore, { Expense } from "@/store/use-config-store";
import { format } from "date-fns";
import { Repeat } from "lucide-react";
import Link from "next/link";

type ExpenseItemProps = {
  expense: Expense;
};

export function ExpenseItem({ expense }: ExpenseItemProps) {
  const { PERSON1, PERSON2 } = useConfigStore();
  const {
    category,
    amount,
    description,
    date,
    paidBy,
    paidFor,
    autoGenerated,
  } = expense ?? {};

  if (!expense) {
    return null;
  }

  const getLabel = (label: string | undefined) => {
    if (!label) return "";
    if (label === PERSONS.PERSON1) return PERSON1;
    if (label === PERSONS.PERSON2) return PERSON2;
    return label;
  };

  const getBgColor = () => {
    if (paidFor === PERSONS.PERSON1) return "bg-blue-50 hover:bg-blue-100/50";
    if (paidFor === PERSONS.PERSON2) return "bg-pink-50 hover:bg-pink-100/50";
    return "bg-green-50 hover:bg-green-100/50";
  };

  return (
    <Link href={`edit-expense?id=${expense.id}`}>
      <Card
        className={`hover:shadow-md transition-all duration-200 border-l-4 border-l-primary/50 ${getBgColor()}`}
      >
        <CardContent className="p-4 flex justify-between items-start">
          <div className="flex flex-col gap-2">
            <div className="flex items-center gap-2">
              <Badge variant="secondary" className="text-xs font-normal">
                {category}
              </Badge>
              {autoGenerated && (
                <Badge
                  variant="outline"
                  className="text-xs font-normal gap-1 px-1.5"
                >
                  <Repeat className="h-3 w-3" />
                  Auto
                </Badge>
              )}
            </div>
            <div>
              <h3 className="font-semibold text-base line-clamp-1">
                {description}
              </h3>
              <p className="text-xs text-muted-foreground mt-0.5">
                {format(new Date(date), "PPP")}
              </p>
            </div>
          </div>

          <div className="flex flex-col items-end gap-1">
            <span className="font-bold text-lg text-primary">
              {getAmountLabel(amount)}
            </span>
            <div className="flex flex-col items-end text-[10px] text-muted-foreground leading-tight">
              <span>
                Paid by <span className="font-medium">{getLabel(paidBy)}</span>
              </span>
              <span>
                For <span className="font-medium">{getLabel(paidFor)}</span>
              </span>
            </div>
          </div>
        </CardContent>
      </Card>
    </Link>
  );
}
