import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { useLongPress } from "@/hooks/use-long-press";
import { PERSONS } from "@/lib/constants";
import { Expense } from "@/lib/types";
import { getAmountLabel } from "@/lib/utils";
import useConfigStore from "@/store/use-config-store";
import { format } from "date-fns";
import { CheckCircle2, Repeat } from "lucide-react";
import { useRouter } from "next/navigation";

type ExpenseItemProps = {
  expense: Expense;
  isSelectionMode?: boolean;
  isSelected?: boolean;
  onToggleSelect?: (id: string) => void;
  onStartSelectionMode?: (id: string) => void;
};

export function ExpenseItem({
  expense,
  isSelectionMode = false,
  isSelected = false,
  onToggleSelect,
  onStartSelectionMode,
}: ExpenseItemProps) {
  const { PERSON1, PERSON2 } = useConfigStore();
  const router = useRouter();

  const {
    category,
    amount,
    description,
    date,
    paidBy,
    paidFor,
    autoGenerated,
  } = expense ?? {};

  const handleLongPress = () => {
    if (!isSelectionMode) {
      onStartSelectionMode?.(expense.id);
    }
  };

  const handleClick = () => {
    if (isSelectionMode) {
      onToggleSelect?.(expense.id);
    } else {
      router.push(`edit-expense?id=${expense.id}`);
    }
  };

  const longPressHandlers = useLongPress({
    onLongPress: handleLongPress,
    onClick: handleClick,
    threshold: 500,
  });

  if (!expense) {
    return null;
  }

  const getLabel = (label: string | undefined) => {
    if (!label) return "";
    if (label === PERSONS.PERSON1) return PERSON1;
    if (label === PERSONS.PERSON2) return PERSON2;
    return label;
  };

  const getBgColor = () => {
    if (isSelected) return "bg-primary/5 hover:bg-primary/10 border-primary";
    if (paidFor === PERSONS.PERSON1) return "bg-blue-50 hover:bg-blue-100/50";
    if (paidFor === PERSONS.PERSON2) return "bg-pink-50 hover:bg-pink-100/50";
    return "bg-green-50 hover:bg-green-100/50";
  };

  return (
    <div
      {...longPressHandlers}
      onContextMenu={(e) => e.preventDefault()}
      className="cursor-pointer select-none touch-none"
    >
      <Card
        className={`hover:shadow-md transition-all duration-200 border-l-4 border-l-primary/50 relative overflow-hidden ${getBgColor()}`}
      >
        <CardContent className="p-4 flex justify-between items-start gap-3">
          <div className="flex items-start gap-3 flex-1 min-w-0">
            {isSelectionMode && (
              <div className="flex items-center justify-center shrink-0 mt-0.5">
                {isSelected ? (
                  <CheckCircle2 className="h-5 w-5 text-primary fill-primary text-white" />
                ) : (
                  <div className="h-5 w-5 rounded-full border-2 border-muted-foreground/30 bg-white" />
                )}
              </div>
            )}
            <div className="flex flex-col gap-2 flex-1 min-w-0">
              <div className="flex items-center gap-2">
                <Badge variant="outline" className="text-xs font-normal bg-white">
                  {category}
                </Badge>
                {autoGenerated && (
                  <Badge
                    variant="outline"
                    className="text-xs font-normal gap-1 px-1.5"
                  >
                    <Repeat className="h-3 w-3" />
                    Auto
                  </Badge>
                )}
              </div>
              <div>
                <h3 className="font-semibold text-base line-clamp-1">
                  {description}
                </h3>
                <p className="text-xs text-muted-foreground mt-0.5">
                  {format(new Date(date), "PPP")}
                </p>
              </div>
            </div>
          </div>

          <div className="flex flex-col items-end gap-1 shrink-0">
            <span className="font-bold text-lg text-primary">
              {getAmountLabel(amount)}
            </span>
            <div className="flex flex-col items-end text-[10px] text-muted-foreground leading-tight">
              <span>
                Paid by <span className="font-medium">{getLabel(paidBy)}</span>
              </span>
              <span>
                For <span className="font-medium">{getLabel(paidFor)}</span>
              </span>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
